language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
matrix:
  allow_failures:
    - node_js: 'iojs'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-drupalpackage' ]; then cd .. && eval "mv $currentfolder generator-drupalpackage" && cd generator-drupalpackage; fi
